apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-dev.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
      - image: docker.elastic.co/beats/filebeat:6.3.2
        name: filebeat
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-claim0
        - mountPath: /var/log
          name: filebeat-claim1
      restartPolicy: Always
      volumes:
      - name: filebeat-claim0
        persistentVolumeClaim:
          claimName: filebeat-claim0
      - name: filebeat-claim1
        persistentVolumeClaim:
          claimName: filebeat-claim1
status: {}
