apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-dev.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:6.3.2
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:5601
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: kibana-claim0
      restartPolicy: Always
      volumes:
      - name: kibana-claim0
        persistentVolumeClaim:
          claimName: kibana-claim0
status: {}
